<?php
ob_start();
require_once "../../db/config.php";
require_once "../../api/staff-api/cashier/reports-b.php";

// Include FPDF
require_once '../../api/fpdf186/fpdf186/fpdf.php'; // Adjust path based on where you placed fpdf.php

// Check if PDF generation is requested
if (isset($_GET['generate_pdf']) && $_GET['generate_pdf'] == '1') {
    // Get filter parameters
    $date_from = $_GET['date_from'] ?? date('Y-m-01');
    $date_to = $_GET['date_to'] ?? date('Y-m-d');
    $payment_type = $_GET['payment_type'] ?? 'all';
    
    // Fetch filtered data
    $transactions = getFilteredTransactions($date_from, $date_to, $payment_type);
    $summary = getSummaryData($date_from, $date_to, $payment_type);
    
    // Generate PDF using FPDF
    generateFPDFReport($transactions, $summary, $date_from, $date_to);
    exit;
}

// Function to get filtered transactions (same as before)
function getFilteredTransactions($date_from, $date_to, $payment_type) {
    global $pdo;
    
    $sql = "SELECT * FROM transactions 
            WHERE date_paid BETWEEN :date_from AND :date_to";
    
    $params = [
        ':date_from' => $date_from . ' 00:00:00',
        ':date_to' => $date_to . ' 23:59:59'
    ];
    
    if ($payment_type != 'all') {
        $sql .= " AND payment_type = :payment_type";
        $params[':payment_type'] = $payment_type;
    }
    
    $sql .= " ORDER BY date_paid DESC";
}

// Function to get summary data (same as before)
function getSummaryData($date_from, $date_to, $payment_type) {
    global $pdo;
    $sql = "SELECT 
                COUNT(*) as total_transactions,
                SUM(amount) as total_amount,
                payment_type,
                COUNT(DISTINCT queue_id) as unique_queues
            FROM transactions 
            WHERE date_paid BETWEEN :date_from AND :date_to";
    
    $params = [
        ':date_from' => $date_from . ' 00:00:00',
        ':date_to' => $date_to . ' 23:59:59'
    ];
    
    if ($payment_type != 'all') {
        $sql .= " AND payment_type = :payment_type";
        $params[':payment_type'] = $payment_type;
    }
    
    $sql .= " GROUP BY payment_type";

}

// Function to generate PDF using FPDF
function generateFPDFReport($transactions, $summary, $date_from, $date_to) {
    ob_end_clean(); // Clean any output buffers
    
    // Create PDF instance
    $pdf = new FPDF('P', 'mm', 'A4');
    $pdf->AddPage();
    
    // Set document properties
    $pdf->SetTitle('Cashier Transaction Report');
    $pdf->SetAuthor('EDUQUEUE System');
    
    // Add College Header
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->Cell(0, 10, 'SAINT LOUIS COLLEGE', 0, 1, 'C');
    $pdf->SetFont('Arial', '', 12);
    $pdf->Cell(0, 6, 'City of San Fernando, La Union', 0, 1, 'C');
    $pdf->SetFont('Arial', 'B', 14);
    $pdf->Cell(0, 10, 'CASHIER TRANSACTION REPORT', 0, 1, 'C');
    $pdf->Ln(5);
    
    // Report Information
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 6, 'Report Period: ' . date('F d, Y', strtotime($date_from)) . ' to ' . date('F d, Y', strtotime($date_to)), 0, 1);
    $pdf->Cell(0, 6, 'Generated On: ' . date('F d, Y h:i A'), 0, 1);
    $pdf->Cell(0, 6, 'Generated By: Cashier Department', 0, 1);
    $pdf->Ln(10);
    
    // Draw a line
    $pdf->SetLineWidth(0.5);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(5);
    
    // Summary Section
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetFillColor(233, 247, 254); // Light blue background
    $pdf->Cell(0, 8, 'REPORT SUMMARY', 0, 1, 'L', true);
    $pdf->Ln(2);
    
    $pdf->SetFont('Arial', '', 11);
    
    $grand_total = 0;
    if (!empty($summary)) {
        foreach ($summary as $item) {
            $grand_total += $item['total_amount'];
            $pdf->Cell(0, 6, $item['payment_type'] . ': ' . $item['total_transactions'] . 
                      ' transactions | Total: ₱' . number_format($item['total_amount'], 2), 0, 1);
        }
        
        $pdf->Ln(3);
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->Cell(0, 6, 'GRAND TOTAL: ₱' . number_format($grand_total, 2), 0, 1);
        $pdf->Cell(0, 6, 'Total Unique Queues Served: ' . (isset($summary[0]['unique_queues']) ? $summary[0]['unique_queues'] : '0'), 0, 1);
    } else {
        $pdf->Cell(0, 6, 'No transactions found for the selected period.', 0, 1);
    }
    
    $pdf->Ln(10);
    
    // Transaction Details Section
    if (!empty($transactions)) {
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetFillColor(233, 247, 254);
        $pdf->Cell(0, 8, 'TRANSACTION DETAILS', 0, 1, 'L', true);
        $pdf->Ln(2);
        
        // Table Header
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->SetFillColor(0, 61, 122); // Dark blue
        $pdf->SetTextColor(255, 255, 255); // White text
        $pdf->Cell(30, 8, 'Trans ID', 1, 0, 'C', true);
        $pdf->Cell(25, 8, 'Queue ID', 1, 0, 'C', true);
        $pdf->Cell(35, 8, 'Amount', 1, 0, 'C', true);
        $pdf->Cell(40, 8, 'Payment Type', 1, 0, 'C', true);
        $pdf->Cell(60, 8, 'Date Paid', 1, 1, 'C', true);
        
        // Table Data
        $pdf->SetFont('Arial', '', 9);
        $pdf->SetTextColor(0, 0, 0); // Black text
        
        $subtotal = 0;
        $fill = false; // For alternating row colors
        $row_count = 0;
        
        foreach ($transactions as $t) {
            $subtotal += $t['amount'];
            
            // Alternate row color
            if ($fill) {
                $pdf->SetFillColor(240, 240, 240);
            } else {
                $pdf->SetFillColor(255, 255, 255);
            }
            $fill = !$fill;
            
            $pdf->Cell(30, 7, $t['transaction_id'] ?? 'N/A', 1, 0, 'C', $fill);
            $pdf->Cell(25, 7, $t['queue_id'] ?? 'N/A', 1, 0, 'C', $fill);
            $pdf->Cell(35, 7, '₱' . number_format($t['amount'] ?? 0, 2), 1, 0, 'R', $fill);
            $pdf->Cell(40, 7, $t['payment_type'] ?? 'N/A', 1, 0, 'C', $fill);
            $pdf->Cell(60, 7, date('M d, Y h:i A', strtotime($t['date_paid'] ?? 'now')), 1, 1, 'C', $fill);
            
            $row_count++;
            
            // Add new page if table gets too long
            if ($pdf->GetY() > 250 && $row_count < count($transactions)) {
                $pdf->AddPage();
                // Re-add table header on new page
                $pdf->SetFont('Arial', 'B', 10);
                $pdf->SetFillColor(0, 61, 122);
                $pdf->SetTextColor(255, 255, 255);
                $pdf->Cell(30, 8, 'Trans ID', 1, 0, 'C', true);
                $pdf->Cell(25, 8, 'Queue ID', 1, 0, 'C', true);
                $pdf->Cell(35, 8, 'Amount', 1, 0, 'C', true);
                $pdf->Cell(40, 8, 'Payment Type', 1, 0, 'C', true);
                $pdf->Cell(60, 8, 'Date Paid', 1, 1, 'C', true);
                $pdf->SetFont('Arial', '', 9);
                $pdf->SetTextColor(0, 0, 0);
            }
        }
        
        // Total Row
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->SetFillColor(233, 247, 254);
        $pdf->Cell(55, 8, 'Total Transactions: ' . count($transactions), 1, 0, 'L', true);
        $pdf->Cell(35, 8, '₱' . number_format($subtotal, 2), 1, 0, 'R', true);
        $pdf->Cell(100, 8, '', 1, 1, 'C', true);
    }
    
    $pdf->Ln(15);
    
    // Footer
    $pdf->SetFont('Arial', 'I', 10);
    $pdf->Cell(0, 5, 'Queuing Management System with Payment Tracking', 0, 1, 'C');
    $pdf->Cell(0, 5, 'Generated by EDUQUEUE System - This is a computer-generated report', 0, 1, 'C');
    $pdf->Cell(0, 5, 'Page ' . $pdf->PageNo(), 0, 1, 'C');
    
    // Output PDF
    $filename = 'cashier_report_' . date('Y-m-d_H-i-s') . '.pdf';
    $pdf->Output('I', $filename); // 'I' sends to browser, 'D' forces download
}

// If not generating PDF, show the filter form (same HTML as before)
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Generate PDF Report - Cashier</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
<link rel="stylesheet" href="../../css/common.css">
<style>
    .report-form-container {
        max-width: 800px;
        margin: 20px auto;
        padding: 30px;
        background: white;
        border-radius: 10px;
        box-shadow: 0 0 15px rgba(0,0,0,0.1);
    }
    .form-section {
        margin-bottom: 30px;
        padding: 20px;
        border: 1px solid #dee2e6;
        border-radius: 8px;
        background: #f8f9fa;
    }
    .btn-generate {
        background: linear-gradient(135deg, #003d7a, #0056b3);
        color: white;
        border: none;
        padding: 12px 40px;
        font-size: 16px;
        border-radius: 5px;
        transition: all 0.3s;
        font-weight: bold;
    }
    .btn-generate:hover {
        background: linear-gradient(135deg, #0056b3, #003d7a);
        transform: translateY(-2px);
        box-shadow: 0 5px 15px rgba(0,61,122,0.3);
    }
    .info-box {
        background: #e9f7fe;
        border-left: 4px solid #003d7a;
        padding: 15px;
        border-radius: 5px;
        margin: 20px 0;
    }
</style>
</head>
<body>
  <?php include __DIR__ . '/../../includes/header.php'; ?>
  <?php include '../../includes/cashier_sidebar.php'; ?>

<div class="main-content" style="margin-left: 240px; padding: 20px;">
  <h1><i class="bi bi-file-earmark-pdf"></i> Generate PDF Report (FPDF)</h1>
  
  <div class="info-box">
    <h5><i class="bi bi-info-circle"></i> About FPDF Reports:</h5>
    <p>• PDFs are generated server-side using FPDF library<br>
       • Reports are automatically downloaded as PDF files<br>
       • No browser printing required<br>
       • Professional formatting with tables and styling<br>
       • Works on all devices without special software</p>
  </div>
  
  <div class="report-form-container">
    <form method="get" action="" id="reportForm">
      <input type="hidden" name="generate_pdf" value="1">
      
      <div class="form-section">
        <h4><i class="bi bi-calendar-range"></i> Select Date Range</h4>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">From Date</label>
            <input type="date" class="form-control" name="date_from" 
                   value="<?php echo date('Y-m-01'); ?>" required>
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">To Date</label>
            <input type="date" class="form-control" name="date_to" 
                   value="<?php echo date('Y-m-d'); ?>" required>
          </div>
        </div>
      </div>
      
      <div class="form-section">
        <h4><i class="bi bi-credit-card"></i> Payment Type Filter</h4>
        <div class="mb-3">
          <select class="form-select" name="payment_type">
            <option value="all">All Payment Types</option>
            <option value="cash">Cash</option>
            <option value="gcash">GCash</option>
            <option value="bank_transfer">Bank Transfer</option>
            <option value="credit_card">Credit Card</option>
            <option value="check">Check</option>
          </select>
        </div>
      </div>
      
      <div class="form-section">
        <h4><i class="bi bi-gear"></i> Report Options</h4>
        <div class="mb-3">
          <label class="form-label">Report Type</label>
          <select class="form-select" name="report_type">
            <option value="detailed">Detailed Report (With Transactions)</option>
            <option value="summary">Summary Only</option>
          </select>
        </div>
        <div class="form-check mb-3">
          <input class="form-check-input" type="checkbox" name="include_header" id="include_header" checked>
          <label class="form-check-label" for="include_header">
            Include College Header
          </label>
        </div>
      </div>
      
      <div class="d-flex justify-content-between mt-4">
        <a href="cashier_report.php" class="btn btn-secondary">
          <i class="bi bi-arrow-left"></i> Back to Reports
        </a>
        <button type="submit" class="btn btn-generate">
          <i class="bi bi-download"></i> Generate & Download PDF
        </button>
      </div>
    </form>
  </div>
  
  <div class="alert alert-success mt-4">
    <h5><i class="bi bi-check-circle"></i> FPDF Features:</h5>
    <div class="row">
      <div class="col-md-6">
        <ul>
          <li>Automatic PDF download</li>
          <li>Professional table formatting</li>
          <li>Alternating row colors</li>
          <li>Automatic page breaks</li>
        </ul>
      </div>
      <div class="col-md-6">
        <ul>
          <li>Custom headers and footers</li>
          <li>Multi-page support</li>
          <li>No external dependencies</li>
          <li>Lightweight and fast</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<?php include "../../includes/footer.php"; ?>

<script>
// Set max date for "to" field to today
document.addEventListener('DOMContentLoaded', function() {
    const dateTo = document.querySelector('input[name="date_to"]');
    dateTo.max = new Date().toISOString().split('T')[0];
    
    const dateFrom = document.querySelector('input[name="date_from"]');
    dateFrom.max = dateTo.value;
    
    dateTo.addEventListener('change', function() {
        dateFrom.max = this.value;
    });
    
    dateFrom.addEventListener('change', function() {
        dateTo.min = this.value;
    });
});
</script>

</body>
</html>